server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:" #use either this optional:configserver:http://localhost:8888 or spring.cloud.config.uri
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: true #Local set it false as App will fail when config server is not running
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 5
#  sql:
#    init:
#      mode: always #Since we are postgres we need to explicitly mention spring.sql.init.mode=always for in-memory DB's it loads by default

management:
  endpoints:
    web:
      exposure:
        include: refresh
polar:
  greeting: Welcome to local book catalog!
  testdata:
    enabled: false